#!/usr/bin/env bash
# ============================================================
# BillingHub ACS — L2TP/IPsec server untuk Summon (NAT traversal)
#
# Pola: MikroTik (tanpa IP publik) = L2TP client → ACS VPS = L2TP server
# Setelah tunnel up, ACS bisa ping IP modem → Summon GenieACS jalan.
#
# Usage (di VPS ACS, sebagai root):
#   sudo BH_L2TP_PSK='rahasia' BH_L2TP_USER='acs-mt' BH_L2TP_PASS='rahasia' \
#        BH_MODEM_SUBNETS='10.10.10.0/24' bash scripts/setup-l2tp-summon.sh
#
# Env opsional:
#   BH_L2TP_LOCAL_IP   default 10.255.255.1
#   BH_L2TP_PEER_IP    default 10.255.255.2
#   BH_L2TP_POOL_START default 10.255.255.2
#   BH_L2TP_POOL_END   default 10.255.255.10
# ============================================================
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Jalankan sebagai root: sudo bash scripts/setup-l2tp-summon.sh" >&2
  exit 1
fi

L2TP_PSK="${BH_L2TP_PSK:?Set BH_L2TP_PSK (IPsec pre-shared key)}"
L2TP_USER="${BH_L2TP_USER:-acs-mt}"
L2TP_PASS="${BH_L2TP_PASS:?Set BH_L2TP_PASS (PPP password)}"
LOCAL_IP="${BH_L2TP_LOCAL_IP:-10.255.255.1}"
PEER_IP="${BH_L2TP_PEER_IP:-10.255.255.2}"
POOL_START="${BH_L2TP_POOL_START:-10.255.255.2}"
POOL_END="${BH_L2TP_POOL_END:-10.255.255.10}"
MODEM_SUBNETS="${BH_MODEM_SUBNETS:-10.10.10.0/24}"

echo "=== Install packages (xl2tpd + strongswan + ppp) ==="
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y xl2tpd strongswan strongswan-pki libcharon-extra-plugins ppp iptables

echo "=== Enable IP forwarding ==="
cat > /etc/sysctl.d/99-billinghub-l2tp.conf <<EOF
net.ipv4.ip_forward=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
EOF
sysctl --system >/dev/null

echo "=== IPsec (strongSwan) — compatible MikroTik L2TP/IPsec ==="
cat > /etc/ipsec.conf <<EOF
config setup
    uniqueids=never
    charondebug="ike 1, knl 1, cfg 0"

conn %default
    keyexchange=ikev1
    authby=secret
    type=transport
    keyingtries=3
    rekey=yes
    forceencaps=yes
    compress=no

conn L2TP-PSK
    keyexchange=ikev1
    left=%any
    leftprotoport=17/1701
    right=%any
    rightprotoport=17/%any
    # Proposal yang cocok MikroTik ROS 6 L2TP/IPsec (PFS group2 di phase2)
    ike=aes128-sha1-modp1024,aes256-sha1-modp1024,aes128-sha1-modp1536,3des-sha1-modp1024!
    esp=aes128-sha1-modp1024,aes256-sha1-modp1024,aes128-sha1,aes256-sha1,3des-sha1-modp1024,3des-sha1!
    auto=add
    dpdaction=clear
    dpddelay=30s
    dpdtimeout=120s
    ikelifetime=8h
    keylife=1h
EOF

cat > /etc/ipsec.secrets <<EOF
: PSK "${L2TP_PSK}"
EOF
chmod 600 /etc/ipsec.secrets

echo "=== xl2tpd + PPP ==="
mkdir -p /etc/ppp/certs
cat > /etc/xl2tpd/xl2tpd.conf <<EOF
[global]
port = 1701
auth file = /etc/xl2tpd/l2tp-secrets
access control = no

[lns default]
ip range = ${POOL_START}-${POOL_END}
local ip = ${LOCAL_IP}
require chap = yes
refuse pap = yes
require authentication = yes
name = BillingHubACS
ppp debug = no
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
EOF

cat > /etc/xl2tpd/l2tp-secrets <<EOF
* * ${L2TP_PASS}
EOF
chmod 600 /etc/xl2tpd/l2tp-secrets

cat > /etc/ppp/options.xl2tpd <<EOF
ipcp-accept-local
ipcp-accept-remote
ms-dns 8.8.8.8
noccp
auth
idle 1800
mtu 1400
mru 1400
nodefaultroute
debug
proxyarp
connect-delay 5000
EOF

# PPP chap secrets — MikroTik user
grep -v "^${L2TP_USER} " /etc/ppp/chap-secrets 2>/dev/null > /tmp/chap-secrets.tmp || true
echo "${L2TP_USER} * ${L2TP_PASS} *" >> /tmp/chap-secrets.tmp
mv /tmp/chap-secrets.tmp /etc/ppp/chap-secrets
chmod 600 /etc/ppp/chap-secrets

echo "=== Firewall UDP 500/4500/1701 ==="
if command -v ufw >/dev/null 2>&1; then
  ufw allow 500/udp comment 'IPsec IKE' || true
  ufw allow 4500/udp comment 'IPsec NAT-T' || true
  ufw allow 1701/udp comment 'L2TP' || true
fi

# Persist routes to modem subnets via peer when tunnel is up (ppp hook)
mkdir -p /etc/ppp/ip-up.d /etc/ppp/ip-down.d
cat > /etc/ppp/ip-up.d/billinghub-modem-routes <<EOF
#!/bin/bash
# \$1=iface \$4=local \$5=remote
IFACE="\$1"
PEER="\$5"
SUBNETS="${MODEM_SUBNETS}"
IFS=',' read -ra NETS <<< "\$SUBNETS"
for net in "\${NETS[@]}"; do
  net=\$(echo "\$net" | xargs)
  [[ -z "\$net" ]] && continue
  ip route replace "\$net" via "\$PEER" dev "\$IFACE" || true
  echo "OK route \$net via \$PEER (\$IFACE)"
done
EOF
chmod +x /etc/ppp/ip-up.d/billinghub-modem-routes

cat > /etc/ppp/ip-down.d/billinghub-modem-routes <<EOF
#!/bin/bash
SUBNETS="${MODEM_SUBNETS}"
IFS=',' read -ra NETS <<< "\$SUBNETS"
for net in "\${NETS[@]}"; do
  net=\$(echo "\$net" | xargs)
  [[ -z "\$net" ]] && continue
  ip route del "\$net" 2>/dev/null || true
done
EOF
chmod +x /etc/ppp/ip-down.d/billinghub-modem-routes

# Save credentials for operators (local only)
install -d -m 700 /opt/genieacs
cat > /opt/genieacs/l2tp-summon.env <<EOF
# Generated by setup-l2tp-summon.sh — jangan commit ke git
BH_L2TP_PSK=${L2TP_PSK}
BH_L2TP_USER=${L2TP_USER}
BH_L2TP_PASS=${L2TP_PASS}
BH_L2TP_LOCAL_IP=${LOCAL_IP}
BH_L2TP_PEER_IP=${PEER_IP}
BH_MODEM_SUBNETS=${MODEM_SUBNETS}
BH_ACS_PUBLIC_IP=$(curl -s4 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
EOF
chmod 600 /opt/genieacs/l2tp-summon.env

systemctl enable strongswan-starter 2>/dev/null || systemctl enable strongswan 2>/dev/null || true
systemctl restart strongswan-starter 2>/dev/null || systemctl restart strongswan 2>/dev/null || ipsec restart
systemctl enable xl2tpd
systemctl restart xl2tpd
sleep 2

echo ""
echo "================================================================"
echo " L2TP/IPsec SERVER SIAP (untuk Summon)"
echo "================================================================"
echo " Connect-to (dari MikroTik) : IP publik VPS ACS"
echo " User PPP                   : ${L2TP_USER}"
echo " Pass PPP                   : (lihat /opt/genieacs/l2tp-summon.env)"
echo " IPsec PSK                  : (lihat /opt/genieacs/l2tp-summon.env)"
echo " Tunnel ACS IP              : ${LOCAL_IP}"
echo " Tunnel peer (MikroTik)     : ${PEER_IP} (pool ${POOL_START}-${POOL_END})"
echo " Modem subnets (auto-route) : ${MODEM_SUBNETS}"
echo ""
echo " MikroTik (ROS 6/7) contoh:"
echo "  /interface l2tp-client add name=l2tp-acs connect-to=<VPS_IP> \\"
echo "    user=${L2TP_USER} password=<PASS> use-ipsec=yes ipsec-secret=<PSK> \\"
echo "    add-default-route=no disabled=no"
echo "================================================================"
systemctl is-active xl2tpd || true
ipsec statusall 2>/dev/null | head -20 || true
